language: go
go:
    - master
install:
    - go get -u github.com/gohugoio/hugo
script:
    - hugo
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    email: $GITHUB_EMAIL
    name: $GITHUB_USERNAME
    verbose: true
    keep-history: true
    local-dir: public
    target_branch: master  # branch contains blog content
    on:
      branch: hugo
