# language: go
# go:
#     - master
# install:
#     - go get -u github.com/gohugoio/hugo
# script:
#     - hugo
# deploy:
#     provider: pages
#     skip-cleanup: true
#     github-token: $GITHUB_TOKEN
#     email: $GITHUB_EMAIL
#     name: $GITHUB_USERNAME
#     verbose: true
#     keep-history: true
#     local-dir: public
#     target_branch: master  # branch contains blog content
#     on:
#       branch: hugo

language: node_js
node_js:
  - 12
cache: 
  directories:
    - node_modules
branches:
  only:
    - hexo
before_install:
  - npm install -g hexo-cli
install:
  - npm install hexo-renderer-jade hexo-renderer-stylus --save
  - npm install gitalk --save
  - npm install hexo-generator-feed --save
  - npm install hexo-generator-search --save
  - npm install

script:
  - hexo clean
  - hexo generate

deploy:
  provider: pages
  email: $GITHUB_EMAIL
  name: $GITHUB_USERNAME
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: true
  local_dir: public
  target_branch: master
  on:
    branch: hexo

notifications:
  email:
    recipients:
      - oliverchangnt@gmail.com
    on_success: change
    on_failure: always

