language: go
go:
    - master
install:
    - mkdir $HOME/src
    - cd $HOME/src
    - git clone https://github.com/gohugoio/hugo.git
    - cd hugo
    - go install --tags extended
script:
    - hugo
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    email: $GITHUB_EMAIL
    name: $GITHUB_USERNAME
    verbose: true
    keep-history: true
    local-dir: public
    target_branch: master  # branch contains blog content
    on:
      branch: hugo
