baseURL = "https://blog.oliverch.com"
languageCode = "zh-cn"
title = "Oliver's Blog!"
theme = "m10c"
paginate = 5

[params]
    author = "Oliver Chang"
    avatar = "https://blog-1252092933.cos.ap-chongqing.myqcloud.com/photo_2018-12-07_00-18-35.jpg"
    subtitle = "I'm here!"
    keywords = "blog,developer,personal"

[[params.social]]
    name = "github"
    url = "https://github.com/Oliver-Chang"

# Brown theme
[params.style]
    darkestColor = "#463625"
    darkColor = "#2a3738"
    primaryColor = "#eeee6a"
    lightColor = "#96a879"
    lightestColor = "#ffffff"
