baseurl = "https://blog.oliverch.com"
languageCode = "zh-cn"
title = "Oliver's Blog!"
theme = "terminal"
paginate = 5

[[params.social]]
    name = "github"
    url = "https://github.com/Oliver-Chang"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = false
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"
    author = "Oliver Chang"
    avatar = "https://blog-1252092933.cos.ap-chongqing.myqcloud.com/photo_2018-12-07_00-18-35.jpg"
    subtitle = "I'm here!"
    keywords = "blog,developer,personal"

[languages]
  [languages.cn]
    title = "Terminal"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.cn.params.logo]
      logoText = "Terminal"
      logoHomeLink = "/"

    [languages.cn.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
