baseURL = "https://blog.oliverch.com"
languageCode = "zh-cn"
title = "Oliver's Blog!"
theme = "m10c"
paginate = 5

[params]
    author = "Oliver Chang"
    avatar = "https://blog-1252092933.cos.ap-chongqing.myqcloud.com/photo_2018-12-07_00-18-35.jpg"
    subtitle = "I'm here!"
    keywords = "blog,developer,personal"

[[params.social]]
    name = "github"
    url = "https://github.com/Oliver-Chang"

[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#fff"
