baseURL = "https://blog.oliverch.com"
languageCode = "zh-cn"
title = "Oliver's Blog!"
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
[params]
    since = 2018
    author = "Oliver Chang"                           # Author's name
    avatar = "https://blog-1252092933.cos.ap-chongqing.myqcloud.com/photo_2018-12-07_00-18-35.jpg"
    subtitle = "I'm here!"
    keywords = "blog,developer,personal"
   
    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.social]
    GitHub = "https://github.com/Oliver-Chang"
    Email   = "mailto:oliverchangnt@gmail.com"


# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
